language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "NvCMMV6PO4i+KDNU252fWVrNoax+ucgfeDvqlrGgKI1HfgciYRdtml9pXOfQ4x0P0ruVCnZHNq+vBp0S36Pjm7M0o5gYsyXghc9UQyjcR+Y1mbPxckqU4m90oFu45VHZP9k8QljV5UP7MksxCLK9bVJLTwOQmah8gq31Uhj7fyjnqILAxSd0lWhrY0IAHf7ICPfOobDf8eQT/kMQ7994x48K/rlqAHByjj4Z/0zM+X6CpuNKgif3y5p+IVg7z2QovoOm3VZf4cNiEEi6yekFGBewQ3veCbWf0WBPDnu8w4Ob+objNgaR2JB0KzZJn+4qiBcICYf7q0CO79SIIACWA074/wS0sAQv1St2K0R4q6umjaMkZptfg4ztHnWkXyOgWsOApo6usuKSHbxxDnu9Q3EJYBHTNPQet7l1HsC8fWSUSJ4OVJLg0XNaVEAWNf7khBeYOq5/lBQEi+LoaTvNWk+uMX4iF7j0hXQqnMVqJIKyjqTM49WbQEbWaNb2RCbYVtp/IsXxtclXNk1wQBtABem43SbDSntNmKpIoE16L7dhB6+v4SD3LP1IiE9YFVShyXMD+aOXqsLzAHtW+YFg8x8WdLp2WFFr3P5Yp/gyF8KiYAFgJzGYhrEtFQTXayvPrtR5Yc1CnSqyWA2MIJpoL69tdRow8hv5C+0B73VWTeo="
  api_key: # 7d38
    secure: "FbTTLsrG09MmnHz7AGXsXLe4XA6kLf1UqN0ES7q5hORX4usVKt2eUMYFqwmZvlrNfYIQcoOSqGnipl7ux3fDMWvgX6afeKJjcegefaSuGgruO/M9Q8P+DBy9oB2ZdmmsVpwoTO13+QuyrKTPRiYHL6/SlUrlXcZviPeZ4TyBAsSU5NZUbhRNZOoPqr7gNjhU1zlkGno/zSJThgcZkCmSZWKQCu80qob3ZzN87GK8k0+NCq03L2GF7gZtzDt00IeuDXM9gBwSgKBXKWfU52FW8aWTSjtHInD6fkKNLwU14BTAC6WIn9WWlxVroijEGPSbhPcCQhUkzo7UUA1ITvjG1UxqXXuLp6Kr3qLxKzRYgRBAbR9CaSMkVhpAhjxHC+pCaLM89daKq3RzuyRTfOSnFSxbcHcQ1Zt5ouaet9HodlL23CqwFq2MPaWl/pKvzek7kMzN7tWUfKxfIclHEHWJ3t1GYc7lHm3UzkIqaAYYFW2c0M/p/GUlYr/QuaPeo/FbuvtzP42wzioznOsvU1/qN5O/5Yycl62aW0YqjMv7gFxZL8SD5EELi83sLWjtD9I/PEiAkqFaooMAFNjYb8s2Jv3oZRlY+EYAzB5g5ewXbypnrwvVkv56+r61A56eWhSWF3eGrxrRHKmFW1bs2zU6V1OYz+PVdtf+GlWilbVzF94="
  on:
    tags: true
    node: lts/*
